UI-Updates-Zhanping-7232023
CodeDayLabs311/cl311 pull request #13
Opened 2023-07-23 05:41 UTC by ZhanpZ

Updated/Implemented from Sophie's PR#10

Added CSS file Report.module.css

Added classNames in ReportEdit.tsx to apply CSS, and changed the ordering of form elements in order to change the look of elements

2023-07-23 05:44 UTC, ZhanpZ commented
![image](https://github.com/CodeDayLabs311/cl311/assets/66219129/aa0e356c-8ed5-4590-a025-d3c32106c0c5)

Currently looking like this, I will update after feedback

2023-07-23 05:54 UTC, ZhanpZ commented
![image](https://github.com/CodeDayLabs311/cl311/assets/66219129/01291584-ea4a-4f49-96e5-c5b34e6ad708)

This is the blue shades version similar to our other page, but the issue is I don't know how to make the cancel/create button look not disturbing but also has enough presence.

2023-07-24 19:29 UTC, ZhanpZ reviewed
Updated the Report.module.css, Sophie provided me with a better design and I think it could be more uniformed if I just use her design.

2023-07-26 18:31 UTC, ZhanpZ commented
![image](https://github.com/CodeDayLabs311/cl311/assets/66219129/03ef7361-0cc6-4a08-82c8-1e99c6c2f25e)
I will change the margin/padding of create button after I make the attachment functionality and see how much space that would take.

2023-07-27 20:28 UTC, andreybutenko requested changes

2023-07-27 20:28 UTC, andreybutenko commented on app/src/components/PageNav.tsx
> +                        <NavLink label="Report" href="/report" />
Instead of replacing guestbook links, do we want to add an additional link to the report page?

2023-07-27 20:28 UTC, andreybutenko commented on app/src/components/report/ReportEdit.tsx
> +export default function ReportEdit({
Nice job! Do you think we should set this up with Formik right away so it's easy to set up validations? Take a look at how Min incorporated Formik  in this PR: https://github.com/CodeDayLabs311/cl311/pull/4

2023-07-27 20:28 UTC, andreybutenko commented on app/src/components/report/ReportEdit.tsx
> +                </Form.Group>
Should we remove this and stick with address for now? It's confusing for the customer to have both. As a separate item, we can make this form accept either an address (type in) or GPS coordinate s(map-picker)

2023-07-27 20:28 UTC, andreybutenko commented on app/src/components/report/ReportEdit.tsx
> +                </Form.Group>
Is there a reason to include this? To me, it seems like a confusing/unnecessary step for our users - Shouldn't the API automatically set the time of submission?

2023-07-27 20:28 UTC, andreybutenko commented on app/src/components/report/ReportEdit.tsx
> +                </Button>
Maybe I don't understand, why is this button here? Shouldn't it be at the bottom of the form?

2023-07-27 20:28 UTC, andreybutenko commented on app/src/components/report/ReportEdit.tsx
> +                    ].map((category, index) => (
Can you please create an enum with these categories? So we can easily use the sam evalues on the frontend and backend :)

2023-07-27 20:28 UTC, andreybutenko commented on app/src/components/report/ReportEdit.tsx
> +                </Form.Group>
Should we hide this section for now, until we have attachment uploading set up?

2023-07-27 20:28 UTC, andreybutenko commented on app/src/components/report/ReportEdit.tsx
> +                </Form.Group>
Is there a reason to include this? I don't think the user should set the status directly during creation, only the city employees reviewing should be able to change the status

2023-07-28 21:35 UTC, ZhanpZ commented on app/src/components/report/ReportEdit.tsx
> +                </Form.Group>
Removed

2023-07-28 21:36 UTC, ZhanpZ commented on app/src/components/PageNav.tsx
> +                        <NavLink label="Report" href="/report" />
Added back

2023-07-28 21:37 UTC, ZhanpZ commented on app/src/components/report/ReportEdit.tsx
> +                </Form.Group>
Removed for now

2023-07-28 21:39 UTC, ZhanpZ commented on app/src/components/report/ReportEdit.tsx
> +                </Form.Group>
Removed

2023-07-28 21:42 UTC, ZhanpZ commented on app/src/components/report/ReportEdit.tsx
> +                </Button>
Changed, I was just trying to have one button on the left and the other on the right column.

2023-07-31 09:28 UTC, closed without merging